/**
 * KORAS Control Plane client for koras-e2e-shop.
 *
 * Generated by create-koras-app (profile: product) because the profile
 * enables the `control_plane_client` capability. The Control Plane profile
 * never generates this package — it is the authority, not a client of one.
 *
 * The registration payload carries infrastructure references only. Secret
 * values must never be sent, logged, or stored here — Doppler is the sole
 * secret authority.
 *
 * **Specification:** `koras-control-plane/docs/PRODUCT_REGISTRATION_CONTRACT.md`.
 * That document is authoritative for both directions. This package is the
 * *outbound* half only — the client for calling the Control Plane. The inbound
 * half, the `/internal/platform/v1/tenants` endpoints the Control Plane calls
 * back into (contract §6), is served by `services/api` and is a different thing
 * that is easy to conflate with this one.
 *
 * The shapes below do not match that contract, and a request built from them is
 * refused. See `docs/SYNC_BACKLOG.md`, A4.
 */

export const PRODUCT_SLUG = 'koras-e2e-shop'
export const REGISTRATION_ENDPOINT = '/api/platform/v1/products'

export interface EnvironmentReference {
  /** dev | test | stg | prod */
  environment: string
  dopplerProject: string
  supabaseProject: string
  flyApps: string[]
}

/** Non-secret infrastructure references sent when registering this product. */
export interface ProductRegistration {
  projectName: string
  projectSlug: string
  profile: string
  githubRepository: string
  zitadelProject: string
  vercelProjects: string[]
  environments: EnvironmentReference[]
}

export interface ControlPlaneClientOptions {
  /** Control Plane base URL, e.g. https://control-plane.koras.io */
  baseUrl: string
  /** Bearer token resolved from Doppler at runtime — never hard-coded. */
  token: string
  fetchImpl?: typeof fetch
}

export class ControlPlaneClient {
  private readonly baseUrl: string
  private readonly token: string
  private readonly fetchImpl: typeof fetch

  constructor(options: ControlPlaneClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, '')
    this.token = options.token
    this.fetchImpl = options.fetchImpl ?? fetch
  }

  async registerProduct(payload: ProductRegistration): Promise<Response> {
    return this.fetchImpl(`${this.baseUrl}${REGISTRATION_ENDPOINT}`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${this.token}`,
      },
      body: JSON.stringify(payload),
    })
  }
}

/** Infrastructure references for this project, fixed at generation time. */
export const registrationContract: Omit<ProductRegistration, 'githubRepository'> = {
  projectName: 'koras-e2e-shop',
  projectSlug: 'koras-e2e-shop',
  profile: 'product',
  zitadelProject: 'koras-e2e-shop',
  vercelProjects: ["koras-e2e-shop-web", "koras-e2e-shop-admin"],
  environments: [
    {
      environment: 'dev',
      dopplerProject: 'koras-e2e-shop-dev',
      supabaseProject: 'koras-e2e-shop-dev',
      flyApps: [],
    },
    {
      environment: 'test',
      dopplerProject: 'koras-e2e-shop-test',
      supabaseProject: 'koras-e2e-shop-test',
      flyApps: [],
    },
    {
      environment: 'stg',
      dopplerProject: 'koras-e2e-shop-stg',
      supabaseProject: 'koras-e2e-shop-stg',
      flyApps: [],
    },
    {
      environment: 'prod',
      dopplerProject: 'koras-e2e-shop-prod',
      supabaseProject: 'koras-e2e-shop-prod',
      flyApps: [],
    },
  ],
}
